import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-bold text-slate-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: January 1, 2025</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-slate-600">
        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing or using TripMind (&quot;the Service&quot;), you agree to be bound by these Terms
            of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">2. Description of Service</h2>
          <p>
            TripMind is an AI-powered travel planning platform that generates personalized
            itineraries, provides destination information, and helps users manage their trips.
            The Service is provided &quot;as is&quot; and may be modified or discontinued at any time.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">3. Account Registration</h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>You must be at least 18 years old to create an account.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You must provide accurate and complete registration information.</li>
            <li>One person may not maintain more than one account.</li>
            <li>You must notify us immediately of any unauthorized use of your account.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">4. Subscriptions and Payments</h2>
          <ul className="list-disc space-y-2 pl-5">
            <li><strong>Free Plan:</strong> Includes limited AI generations and basic features at no cost.</li>
            <li><strong>Pro Plan:</strong> Billed monthly at $19. Cancel anytime. Refunds handled per our refund policy.</li>
            <li><strong>Credits Pack:</strong> One-time purchase of AI generation credits. Non-refundable once used.</li>
            <li>All payments are processed securely through Stripe.</li>
            <li>Prices may change with 30 days notice to existing subscribers.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">5. AI-Generated Content</h2>
          <p>
            Itineraries and recommendations generated by our AI are provided for informational
            purposes. While we strive for accuracy, we cannot guarantee that all information
            (prices, hours, availability) is current or error-free. You are responsible for
            verifying critical details before travel.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">6. User Conduct</h2>
          <p>You agree not to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>Use the Service for any unlawful purpose.</li>
            <li>Attempt to gain unauthorized access to any part of the Service.</li>
            <li>Interfere with or disrupt the Service or servers.</li>
            <li>Use automated tools (bots, scrapers) to access the Service.</li>
            <li>Reproduce, duplicate, or resell any part of the Service without authorization.</li>
            <li>Use the Service to send spam or unsolicited communications.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">7. Intellectual Property</h2>
          <p>
            The Service, including its design, code, content, and AI models, is owned by TripMind
            and protected by intellectual property laws. You retain ownership of data you input
            into the Service. You grant us a limited license to use your data to provide and
            improve the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, TripMind shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including but not limited to
            loss of profits, data, or travel expenses, arising from your use of the Service.
            Our total liability shall not exceed the amount you paid us in the 12 months preceding
            the claim.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">9. Termination</h2>
          <p>
            We may suspend or terminate your account at any time for violation of these Terms.
            You may delete your account at any time from your settings. Upon termination, your
            right to use the Service ceases immediately.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. Material changes will be
            communicated via email or through the Service. Continued use after changes take
            effect constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">11. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the jurisdiction in which TripMind operates,
            without regard to conflict of law principles.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-slate-900">12. Contact</h2>
          <p>
            Questions about these Terms? Contact us at{" "}
            <a href="mailto:legal@tripmind.ai" className="text-primary-500 hover:text-primary-600 underline">
              legal@tripmind.ai
            </a>.
          </p>
        </section>
      </div>

      <div className="mt-12 border-t border-slate-200 pt-8 text-center text-sm text-slate-500">
        <Link href="/" className="text-primary-500 hover:text-primary-600">
          Back to Home
        </Link>
      </div>
    </div>
  );
}
